# ansible 初始化生产微服务机
- hosts: newserver
  vars:
    basedir: [yantao,jianghy,menglq,gongyong,yutang]
  tasks:
    - name: 安装常用依赖环境
      yum: name={{ item }} state=present
      with_items:
        - lrzsz
        - telnet
        - wget
        - epel-release

    - name: 为所有创建的新用户添加属组
      group:
        name: develop
        state: present

    - name: 为所有用户添加sudo权限
      shell: /usr/bin/sed -i '94i %develop  ALL=(ALL)       NOPASSWD:ALL ' /etc/sudoers
    - name: 创建常用用户
      user: name={{ item }} state=present group=develop
      with_items:
        - yutang
        - yantao
        - jianghy
        - menglq
        - gongyong

    - name: 创建用户密钥目录
      file: path=/home/{{ item }}/.ssh/ state=directory  owner={{ item }} group=develop mode=0700
      with_items:
        - yutang
        - yantao
        - jianghy
        - menglq
        - gongyong

    - name: 创建用户密钥文件
      file: path=/home/{{ item }}/.ssh/authorized_keys state=touch  owner={{ item }} group=develop mode=0600
      with_items:
        - yantao
        - jianghy
        - menglq
        - gongyong
        - yutang

    - name: 添加老监控密钥远程登录权限
      lineinfile:
        dest=/home/yutang/.ssh/authorized_keys
        line="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3BYfaoYkpK6nSLCJ9oXrJFyP4N9KSPdbfsrj1A4J4nnaVdJ/ZNrYMXUSLCZKEjZ9lGg7B3uRAH+r1D/tNmAjy58NsXNLT0oKmDGaOG5RcGWhEpVMKh9RQISySRbFa1wkk2hV1VebkY4VXPjZAVJneA7wO+grBdLoINJpeAy5hf4FB1HvuJwqZQqgXiiJPx8Coe6HJ02V325+5KY2XgQbfFddwdkPKjaVuC9UWwED3+w07yW1xYwU6AJhWefFXmKbhn+Tj1tquR2NHQz5H7xK+BuXFfa/Qz72tRYHhwAYQdz8jL1QMKxYQ/mbSWlTpb8WwXD2SW3b1uFGOJt0R+wH7 yutang@yutang-monitor"
    - name: 添加机房Jenkins远程登录权限
      lineinfile:
        dest=/home/yutang/.ssh/authorized_keys
        line="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCn6ux9wR7832yI8jAtS6oCH+539NYPClV8FugAQMDeyiqT12xsGNq+SSLtfXTzXcSunHZz/Pn4D9bsarLUuxd/Z6MJbQfPfL3gdvTt81zMVwJrTEqtuxp8xw7iA+w7pHX41nmtb4Ccu61L4tqc2GPzIB4QVaO+qS/uBSEccG7UugTKfTxBBHSxLKmmPwIPnjRPeAkPM8IDvtfccqKCmmphDoIrCiRbe0Vc+R/iD97S7YCerhFRsJvB+FwUXGRNwpszXFjsAdw0rH7CIrlSDqGcGctO339rBxF8NbkE5Rxgig9+NnfASOkHWxMZ/ZOdluwSZG+gsLQUT70np9nbsRDN root@dev-server-04"
    - name: 添加闫涛密钥登录权限
      lineinfile:
        dest=/home/yantao/.ssh/authorized_keys
        line="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKlJ2mw9ZjUlqXq4xHXoxB6AYaSW7dNJz7BSt575/lVKB+lnrwsnMzDm6Uw9bKPdSQI1ZN0LSciv52IkLiC6K5YYRcM/34zF4sxsHdlwgzR0rfW4eom4TKh8O00Qdui8iEpXcsxRdTzdap5Hx+gYXvWbxy3UVJeLXZsZdLmM78yjfNDWfglSh385cJgCoX8nySxaIMKQgAAYSkbeEQXtPIQZg4jRHeykrHdgr6C9Y9LAWwwr3QUl4eq2EfpyZKrhO8EbKM8+LOOiD2wfZAYtD/sjXV0vZ17SdN3kuGCa2W9GSJBnOTYN9Gjwpd4UB6FM/9etbiArHlbfw1U1LpyYST yantao@yantao"
    - name: 添加添加江海洋密钥登录权限
      lineinfile:
        dest=/home/jianghy/.ssh/authorized_keys
        line="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNCJY3F97GH9/lwEZAKWJkQ/7NYQ78TJwAyHYuaQ8EAg+eF2x9NFuUgtz1gs2kC12xWSvduxJ9/58mtVj1pX/cs07m5OBEMEfuXlF/KsL/uBvxJ2kytCp3ke1Lp7sKTJKUV+qWZB6UXOHRFPstMFKSbuaqzp3E8h+nSboluGq0DgbWchWGFSu03uPTZwodyRU2Ed2R6Smj5hfGfj72SPyYZNJCKah21ovrsTj67gXrvp/5CYgPnAEuVFgT2dmj6MEGagyvwuh4i52FksMUoF4D+Wk76njLXPiVvOVn+tFDuq6Ts7isO2pIrm0BTLQwu/0YoRVzNtL7mbCZe4KPJWc9 yangzhi@yangzhi"
    - name: 添加添加孟令琪密钥登录权限
      lineinfile:
        dest=/home/menglq/.ssh/authorized_keys
        line="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQXj+RWZYkio3xzJK+3bs4cWra7xQbWNcRe8GOCwTaAoIZ92iZox2+rCzUlzsutmQqlYk3ndasmIMgKLMfqdQ42TijX7kBrFoPJsQHCVR7+TC02P7Vmh4akwtJQLOfC1Ky3Q/L7sfpfp5YTQz3Cpu5UlQfuaeeipIawjVqea6zyqd0+EHblPM3Bf1GZDBuyKHH6ldNSCCyaVDS/8MbupZz6O2/LHO6LF9BthqrMmcEyMSIXcqWxjk2HJnRTQ0gj2Rn7jPwdVHQ0bpU4PcYAy0c6yLA51W+QkNKuskAF9CdNQToQMjOlNoqpAGDAP6/pMzqfmleJZ12R134omCEUy97 menglingqi@menglingqi"
    - name: 添添加龚勇密钥登录权限
      lineinfile:
        dest=/home/gongyong/.ssh/authorized_keys
        line="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOP5yLE7sWjrnimHq/JSL2QDYGmz4zSuLt9OeWBavvUc5+Tjmz8eSPBhgqgz+ZDiUXUlPfn8pf8M/oM8XFUgOGGG8GlC1fjWbSs7WW8BN/F9d69f1KHpaKAyB7XItfzy52JHjGShm8QHwD096mL+4wbqdKTo9alZoiQmN/q3Sver526d/KBP0q+VtLv93vJRt/frOL4UmEQkNaKsFxovMIesiUnxwYEjQLWyvTUhfl6FiE6QpvKADEAy7v6a25DK3MW/nG30hJAhbBHtduCelKGi4eFEYQJVinTJyqwL5LOKe7NDXHGkplRz1uPhiImF9NIAeMSz/Ux/O03ObjfF3N gongyong@gongyong"

    - name: 创建微服务基本运行父级目录环境
      file: path=/alidata/{{ item }}/ state=directory  owner=yutang group=develop mode=0755
      with_items:
        - service
        - server
        - src

    - name: 创建微服务基本运行子级server目录环境
      file: path=/alidata/server/{{ item }}/ state=directory  owner=yutang group=develop mode=0755
      with_items:
        - backup
        - config
        - download
        - tmps
        - src

    - name: 创建微服务基本运行子级service目录环境
      file: path=/alidata/service/{{ item }}/ state=directory  owner=yutang group=develop mode=0755
      with_items:
        - tmp
        - logs

    - name: 下载jdk环境
      get_url: url=http://mirror.cnop.net/jdk/linux/jdk-8u112-linux-x64.tar.gz dest=/alidata/server/src mode=0655 force=yes owner=yutang
    - name: 解压jdk压缩包
      unarchive: src=/alidata/server/src/jdk-8u112-linux-x64.tar.gz dest=/alidata/server/ mode=0755 copy=no

    - name: 授权所有目录权限为yutang
      shell: chown -R yutang.develop /alidata

    - name: 添加jdk环境变量
      lineinfile: dest=/etc/profile  line="export JAVA_HOME=/alidata/server/jdk1.8.0_112"
    - name: 添加jdk环境变量
      lineinfile: dest=/etc/profile  line="export PATH=$JAVA_HOME/bin:$PATH"
    - name: 刷新java环境变量
      shell: source /etc/profile

    - name: 将本地config文件传输到远程服务器
      copy: src=/alidata/server/config.tar.gz dest=/alidata/server/ owner=yutang group=develop mode=0755
    - name: 将本地logstash文件传输到远程服务器
      copy: src=/alidata/server/logstash.tar.gz dest=/alidata/server/ owner=yutang group=develop mode=0755

    - name: 解压config压缩包
      unarchive: src=/alidata/server/config.tar.gz dest=/alidata/server/ mode=0755 owner=yutang group=develop copy=no

    - name: 解压logstash压缩包
      unarchive: src=/alidata/server/logstash.tar.gz dest=/alidata/server/ mode=0755 owner=yutang group=develop copy=no

    - name: 移动config.tar.gz和ogstash.tar.gz到/alidata/server/download备份目录下
      shell: /usr/bin/mv /alidata/server/*.gz /alidata/server/download/

    - name: 修改主机名
      raw: "echo {{hostname|quote}} > /etc/hostname"
    - name: 设置主机名
      shell: hostname {{hostname|quote}}
    - name: 显示主机名
      shell: /usr/bin/cat /etc/hostname

    - name: 定时清理系统缓存
    cron: name="每隔1小时清理一次系统缓存" job="/usr/bin/sync; /usr/bin/echo 3 > /proc/sys/vm/drop_caches" minute=*/60 state=present
