# ansible 初始化测试微服务机
- hosts: newserver
  vars:
    - basedir: data
  tasks:
    - name: 安装常用依赖环境
      yum: name={{ item }} state=present
      with_items:
        - lrzsz
        - telnet
        - wget
        - epel-release

    - name: 为所有创建的新用户添加属组
      group:
        name: develop
        state: present
    - name: 将yutang用户加入develop组
      shell: usermod -G develop yutang

    - name: 创建微服务基本运行父级目录环境
      file: path=/{{ basedir }}/{{ item }}/ state=directory  owner=yutang group=develop mode=0755
      with_items:
        - service
        - server
        - src

    - name: 创建微服务基本运行子级server目录环境
      file: path=/{{ basedir }}/server/{{ item }}/ state=directory  owner=yutang group=develop mode=0755
      with_items:
        - backup
        - config
        - download
        - tmps
        - src

    - name: 创建微服务基本运行子级service目录环境
      file: path=/{{ basedir }}/service/{{ item }}/ state=directory  owner=yutang group=develop mode=0755
      with_items:
        - tmp
        - logs

    - name: 下载jdk环境
      get_url: url=http://mirror.cnop.net/jdk/linux/jdk-8u112-linux-x64.tar.gz dest=/{{ basedir }}/server/src mode=0655 force=yes owner=yutang
    - name: 解压jdk压缩包
      unarchive: src=/{{ basedir }}/server/src/jdk-8u112-linux-x64.tar.gz dest=/{{ basedir }}/server/ mode=0755 copy=no

    - name: 添加jdk环境变量
      lineinfile: dest=/etc/profile  line="export JAVA_HOME=/data/server/jdk1.8.0_112"

    - name: 添加jdk环境变量
      lineinfile: dest=/etc/profile  line="export PATH=$JAVA_HOME/bin:$PATH"


    - name: 将本地logstash文件传输到远程服务器
      copy: src=/{{ basedir }}/server/logstash.tar.gz dest=/{{ basedir }}/server/ owner=yutang group=develop mode=0755

    - name: 解压logstash压缩包
      unarchive: src=/{{ basedir }}/server/logstash.tar.gz dest=/{{ basedir }}/server/ mode=0755 owner=yutang group=develop copy=no

    - name: 将本地pinpoint文件传输到远程服务器
      copy: src=/{{ basedir }}/server/pinpoint-agent.tar.gz dest=/{{ basedir }}/server/ owner=yutang group=develop mode=0755

    - name: 解压pinpoint压缩包
      unarchive: src=/{{ basedir }}/server/pinpoint-agent.tar.gz dest=/{{ basedir }}/service/ mode=0755 owner=yutang group=develop copy=no

    - name: 将本地consul文件传输到远程服务器
      copy: src=/{{ basedir }}/server/consul.tar.gz dest=/{{ basedir }}/server/ owner=yutang group=develop mode=0755

    - name: 解压consul压缩包
      unarchive: src=/{{ basedir }}/server/consul.tar.gz dest=/{{ basedir }}/server/ mode=0755 owner=yutang group=develop copy=no


    - name: 移动config.tar.gz和ogstash.tar.gz到/alidata/server/download备份目录下
      shell: /usr/bin/mv /{{ basedir }}/server/*.gz /{{ basedir }}/server/download/

    - name: 授权所有目录权限为yutang
      shell: chown -R yutang.develop /{{ basedir }}


    - name: 修改主机名
      raw: "echo {{hostname|quote}} > /etc/hostname"

    - name: 设置主机名
      shell: hostname {{hostname|quote}}

    - name: 刷新java环境变量
      shell: source /etc/profile

    - name: 定时清理系统缓存
      cron: name="每隔1小时清理一次系统缓存" job="/usr/bin/sync; /usr/bin/echo 3 > /proc/sys/vm/drop_caches" minute=*/60 state=present
